### ISSUE TITLE
Index.php will not load

### ISSUE THREAD

**Issue by thenoelman** [pavulon18/gcas_timesheet_php_website#37]
## Expected Behavior

The home page should load

## Actual Behavior

An error message appears:

Warning: require(config.php): failed to open stream: No such file or directory in C:\xampp\htdocs\gcas_timesheet_php_website\index.php on line 38

Fatal error: require(): Failed opening required 'config.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\gcas_timesheet_php_website\index.php on line 38

![indexphperror](https://user-images.githubusercontent.com/16550366/39163787-e9cdebe6-4730-11e8-9a39-b56b86344bea.jpg)

## Steps to Reproduce the Problem

  1.  Clone the project
  1.  Startup xampp
  1.  Go to the home page

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by thenoelman** [comment]
I figured out the solution to this issue.  You have to move config.php from \bower_components\jquery-hashchange\examples out  to the root directory.

**Comment by pavulon18** [comment]
That is not the correct config file.

**Comment by pavulon18** [comment]
https://github.com/pavulon18/gcas_timesheet_php_website/blob/master/config_example.php

This is a sample of the correct config file.  It should be already in the root directory.  You'll need to change the name from "config_example.php" to "config.php"
