### ISSUE TITLE
schema.sql error messages

### ISSUE THREAD

**Issue by thenoelman** [pavulon18/gcas_timesheet_php_website#39]
## Expected Behavior

I'm trying to create a local copy of your mysql database.  I created a new database and then attempted to run schema.sql (which looks like it should create all the tables).

## Actual Behavior

I got the attached error message:

![sqlerror](https://user-images.githubusercontent.com/16550366/39164538-c66634fc-4734-11e8-8179-e68ef693854c.jpg)

## Steps to Reproduce the Problem

  1. Setup a new database (locally)
  1. Run schema.sql
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by pavulon18** [comment]
Hmm.. Interesting.  Let me make sure I have the appropriate sql uploaded.

**Comment by thenoelman** [comment]
Fixed.  You should run the file:

GCEMS_empty_db.sql

**Comment by thenoelman** [comment]
@pavulon18 This is a reminder for you to not to forget to put GCEMS_empty_db.sql on github at some point.

**Comment by pavulon18** [comment]
The most recent db schema is queued to be uploaded when I do my next upload.

I'll also need to update the README to reflect this.

**Comment by pavulon18** [comment]
I'm going to close this since the updated schema file fixed your issue.
