### ISSUE TITLE
Employees page- bullets not aligned

### ISSUE THREAD

**Issue by thenoelman** [pavulon18/gcas_timesheet_php_website#41]
## Expected Behavior

Again, a minor css issue.  On the Employee's page, the bullet points are not aligned.  

![employees page bullet-css](https://user-images.githubusercontent.com/16550366/39166718-fee0e6aa-473f-11e8-984e-9e1d6c6df944.jpg)

**Comment by pavulon18** [comment]
I agree.  The layout of those need some help.  There will probably be more links added before I'm done.  These links will need to be rearranged and grouped a lot better.

**Comment by pavulon18** [comment]
Fixed the alignment of the links as well as reformatted the text block.  They are queued to be uploaded the next time I push changes to Github.
