### ISSUE TITLE
Can't get logins to work when running locally

### ISSUE THREAD

**Issue by thenoelman** [pavulon18/gcas_timesheet_php_website#45]
## Expected Behavior

The login screen prompts me for a username and a password

## Actual Behavior

It looks like it's redirecting me to http://gcastimesheetemployees/login and I get a "server not found" error.

![local_login issues](https://user-images.githubusercontent.com/16550366/39225777-22dbc3d6-4803-11e8-9622-102fb8c0e21b.jpg)

## Steps to Reproduce the Problem

  1.  Startup xampp
  1.  Go to the website and click on login

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by pavulon18** [comment]
I've received no further feedback on this bug.  I am going to close this issue.  If someone still finds this to be an issue, please open another report.
